const { service, today, showError } = require('../../lib/core');
Page({
  data: { error: '', id: '', conversation: null, messages: [], runs: [], question: '', previewData: null, label: '', cloud: false, busy: false },
  async onLoad(options = {}) { this.setData({ id: options.id || '' }); const capability = await service.ai().capabilities(); this.setData({ label: capability.label, cloud: capability.enabled && capability.providerConfigured && capability.enrolled }); this.refresh(); },
  onShow() { if (this.data.id) this.refresh(); },
  refresh() { try { const view = service.ai().conversation(this.data.id); if (this._workspaceInstance && this._workspaceInstance !== view.conversation.workspace_instance_id) this.invalidate(); this._workspaceInstance = view.conversation.workspace_instance_id; const sources = new Map((view.sources || []).map(source => [source.id, source])); const runs = view.runs.map(run => ({ ...run, contextLabel: view.conversation.context_mode === 'historical' ? '历史回看' : '当前分析', evidence: run.result.evidence || [], counterarguments: run.result.counterarguments || [], missing: run.result.missing_information || [], sourceDetails: run.source_ids.map(id => sources.get(id)).filter(Boolean).map(source => ({ ...source, quote: source.type === 'quote' ? (() => { try { return JSON.parse(source.content); } catch (_) { return null; } })() : null })) })); this.setData({ conversation: view.conversation, messages: view.messages, runs, error: '' }); } catch (e) { this.setData({ error: e.message }); } },
  invalidate() { this._draftRevision = (this._draftRevision || 0) + 1; this._previewRevision = null; this._confirmedInput = null; this._confirmedPreview = null; this.setData({ previewData: null }); },
  onQuestion(e) { this.setData({ question: e.detail.value }); this.invalidate(); },
  input() { const current = service.ai().conversation(this.data.id).conversation; const instrument = current.origin === 'instrument' && current.anchor_id ? service.ai().confirmResearchInstrument(current.anchor_id, 'STOCK') : undefined; return { origin: current.origin, conversationId: current.id, anchorId: current.anchor_id, instrument, mode: 'follow_up', journalDate: today(), question: this.data.question, includeHistory: true }; },
  preview() { try { if (!this.data.question.trim()) throw Error('请先填写追问。'); const input = this.input(); const preview = service.ai().previewContext(input); this._confirmedInput = input; this._confirmedPreview = preview; this._previewRevision = this._draftRevision || 0; this.setData({ previewData: { ...preview, missingText: preview.missingInformation.join('、') }, error: '' }); } catch (e) { this.setData({ error: e.message }); showError(e); } },
  async send() { if (this.data.busy) return; try { if (!this._confirmedInput || this._previewRevision !== (this._draftRevision || 0)) throw Error('请先查看本次追问将使用的信息。'); let capability = await service.ai().capabilities(); if (!capability.enabled || !capability.providerConfigured || !capability.enrolled) throw Error(capability.label); if (!capability.consented) { const accepted = await new Promise(resolve => wx.showModal({ title: '确认使用云端 AI', content: '本轮会把预览中的持仓信息、所选个人内容、问题和会话历史发送到本项目云服务和模型服务。你可以取消并继续使用本地记录。', confirmText: '同意并继续', success: result => resolve(result.confirm), fail: () => resolve(false) })); if (!accepted) throw Error('已取消云端处理。'); capability = await service.ai().acceptConsent(capability.consentVersion); } if (!capability.authorized) throw Error(capability.label); this.setData({ busy: true }); const prepared = service.ai().prepare(this._confirmedInput, this._confirmedPreview); this._confirmedInput = null; this._confirmedPreview = null; this._previewRevision = null; this.setData({ previewData: null }); const result = await service.ai().submitPrepared(prepared); if (result?.conversation) { this.setData({ question: '' }); this.refresh(); wx.showToast({ title: '已保存' }); } else wx.showToast({ title: '已提交，请到投研页查询', icon: 'none' }); } catch (e) { this.setData({ error: e.message }); showError(e); } finally { this.setData({ busy: false }); } },
});
