const { service, today, showError } = require('../../lib/core');
Page({
  data: { error: '', capability: null, mode: 'portfolio_review', journalDate: '', symbol: '', question: '我的持仓有哪些需要注意？', previewData: null, result: null, conversationId: '', recent: [], candidateUnavailable: false },
  onLoad(options = {}) { this.setData({ journalDate: options.date || today(), mode: options.mode || (options.symbol ? 'instrument_research' : 'portfolio_review'), symbol: options.symbol || '', question: options.mode === 'daily_review' ? '请根据已选的当日记录帮我复盘。' : this.data.question }); },
  onShow() { try { const state = service.journal().read(); this.setData({ capability: service.ai().capabilities(), recent: state.runs.slice().reverse().slice(0, 5).map(run => ({ id: run.id, conversationId: run.conversation_id, date: run.journal_date, summary: run.result.summary, demo: run.demo })), error: '' }); } catch (e) { this.setData({ error: e.message }); } },
  selectPortfolio() { this.setData({ mode: 'portfolio_review', candidateUnavailable: false, previewData: null, result: null }); },
  selectInstrument() { this.setData({ mode: 'instrument_research', candidateUnavailable: false, previewData: null, result: null }); },
  selectCandidate() { this.setData({ candidateUnavailable: true, previewData: null, result: null }); },
  onSymbol(e) { this.setData({ symbol: e.detail.value.toUpperCase(), previewData: null }); },
  onQuestion(e) { this.setData({ question: e.detail.value, previewData: null }); },
  preview() { try { const anchorId = this.data.mode === 'instrument_research' ? service.ai().confirmResearchInstrument(this.data.symbol, 'STOCK').symbol : null; const preview = service.ai().previewContext({ mode: this.data.mode, journalDate: this.data.journalDate, question: this.data.question, anchorId }); this.setData({ previewData: { ...preview, missingText: preview.missingInformation.join('、') }, error: '' }); } catch (e) { showError(e); } },
  runDemo() { try { if (!this.data.previewData) this.preview(); const anchorId = this.data.mode === 'instrument_research' ? service.ai().confirmResearchInstrument(this.data.symbol, 'STOCK').symbol : this.data.mode === 'daily_review' ? this.data.journalDate : null; const result = service.ai().analyze({ origin: this.data.mode === 'instrument_research' ? 'instrument' : this.data.mode === 'daily_review' ? 'daily_review' : 'portfolio', anchorId, mode: this.data.mode, journalDate: this.data.journalDate, question: this.data.question }); this.setData({ result: result.result, conversationId: result.conversation.id }); wx.navigateTo({ url: `/pages/conversation/index?id=${encodeURIComponent(result.conversation.id)}` }); } catch (e) { showError(e); } },
  openConversation(e) { wx.navigateTo({ url: `/pages/conversation/index?id=${encodeURIComponent(e.currentTarget.dataset.id)}` }); },
});
